### ISSUE TITLE
Failure to mount when aws config file present

### ISSUE THREAD

**Issue by guba-elleschr** [awslabs/mountpoint-s3-csi-driver#232]
/kind bug

**What happened?**
s3-mount fails to mount bucket, generating a core dump and a memory allocation error when an AWS config file is present.
```
Jul 24 00:00:51 kube2-test systemd[1]: Starting Mountpoint for Amazon S3 CSI driver FUSE daemon...
Jul 24 00:00:51 kube2-test systemd[1]: Started Process Core Dump (PID 1298945/UID 0).
Jul 24 00:00:51 kube2-test systemd-coredump[1298946]: Process 1298938 (mount-s3) of user 0 dumped core.
Jul 24 00:00:51 kube2-test kubelet[1289]: E0724 00:00:51.456766    1289 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/s3.csi.aws.com^s3-csi-driver-volume podName: nodeName:}" failed. No retries permitted until 2024-07-24 00:02:53.456746942 -0400 EDT m=+117682.745804296 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "s3-gubaredis-pv" (UniqueName: "kubernetes.io/csi/s3.csi.aws.com^s3-csi-driver-volume") pod "s3-app" (UID: "ed83819b-095e-44d7-99a7-1c1a4858ff33") : rpc error: code = Internal desc = Could not mount "gubaredis" at "/var/lib/kubelet/pods/ed83819b-095e-44d7-99a7-1c1a4858ff33/volumes/kubernetes.io~csi/s3-gubaredis-pv/mount": Mount failed: Failed to start service output: malloc failed to allocate memoryError: Failed to create mount process
```

This mounts fine when using s3-mount directly on the node, it only fails when mounted via csi driver.

It also mounts fine immediately after deleting the `/root/.aws/config` file.

**What you expected to happen?**
The csi driver ignores the AWS config file, uses the `aws-secret` secret and mount succeeds regardless of AWS config file.

**How to reproduce it (as minimally and precisely as possible)?**
Follow driver installation instructions and static provisioning example https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md

Add config file for AWS:
```
root@kube2-test:~# cat /root/.aws/config
[default]
output = plain
region = us-east-1
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): `v1.30.1`
- Driver version: `aws-mountpoint-s3-csi-driver-1.7.0`

**Comment by unexge** [comment]
Hey @guba-elleschr, thanks for reporting the issue, and sorry for the inconvenience!

I was able to reproduce the issue, in my case [CRT](https://docs.aws.amazon.com/sdkref/latest/guide/common-runtime.html) was crashing because `AWS_ROLE_ARN` was empty. We always pass `AWS_ROLE_ARN` if  `AWS_WEB_IDENTITY_TOKEN_FILE` is not empty without checking [`AWS_ROLE_ARN`'s value](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/pkg/driver/mount.go#L67-L70), and it causes empty `AWS_ROLE_ARN` in some cases I think.

I'll work on finding the best place to fix the issue (CSI driver vs CRT).

Meanwhile, to unblock yourself, I was able to make it work by setting a dummy value for `AWS_ROLE_ARN`, could you please try the same and check if that prevents CSI driver from crashing please?

You can update CSI driver's service account role by (again role can be anything as long as it's not empty):
```bash
$ kubectl annotate serviceaccount s3-csi-driver-sa "eks.amazonaws.com/role-arn"="arn:aws:iam::account:role/DummyRoleName" -n kube-system # You might need "--overwrite" here
```

You also need to make sure to refresh CSI driver's Pods by killing existing Pods and letting CSI driver's DaemonSet to create new Pods if your workflow allows that.

**Comment by unexge** [comment]
The issue is fixed on CRT side, we'll include latest CRT version with our next release.

**Comment by guba-elleschr** [comment]
Hey @unexge, thanks for looking into this.  

I've tried adding the annotation and restarting the pods as suggested but I'm still experiencing the `malloc failed to allocate memory` errors.  

I've also tried removing the install and reinstalling while declaring the role-arn with the same results.
`helm upgrade --install aws-mountpoint-s3-csi-driver     --namespace kube-system   --set node.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::account:role/csi-driver-role-name"  aws-mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver`

Do you have any other suggestions on what it could be?

**Comment by unexge** [comment]
Hey @guba-elleschr, so I think the current bug occurs when CRT cannot find all configuration values from env variables and tries to load them from profile file, and it crashes if it cannot find those values from the profile file as well.

So if you try to provide [all values](https://github.com/awslabs/aws-c-auth/blob/main/source/credentials_provider_sts_web_identity.c#L1006-L1009) for:
- `region`
- `role_arn`
- `role_session_name`
- `web_identity_token_file`

in your profile file, it might not crash. 

Also, this bug is fixed in CRT, and we'll include the fixed CRT version in our next release.

**Comment by guba-elleschr** [comment]
Thanks @unexge, setting `role_arn` in the AWS profile config worked for me!

**Comment by unexge** [comment]
[v1.8.0](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/CHANGELOG.md#v180) has been released with a fix for this issue. Closing this ticket now, please let us know if you encounter the same problem again with 1.8.0.
